### ISSUE TITLE
`swift run` usage suggestion should be fixed

### ISSUE THREAD

**Issue by valeriyvan** [apple/swift-driver#1515]
`swift run -help` give following:

```
swift run -help      
OVERVIEW: Build and run an executable product

SEE ALSO: swift build, swift package, swift test

USAGE: swift run [<options>] [<executable>] [<arguments> ...]

<rest of output is omitted>
```

Suggested usage is not quite correct. If there's a need to pass some arguments to executable there's no other way as explicitly use <executable> otherwise all <arguments> are treated as <options> which are passed to driver. I believe correct usage suggestion should be as follows:

```
USAGE: swift run [<options>] [<executable> [<arguments> ...]]
```

**Comment by MaxDesiatov** [comment]
I don't think this was filed on the correct repository, `swift run` is a SwiftPM command and is not related to Swift Driver. I'm also not sure what is being suggested here. If you see an issue with `swift run`, please file it in the SwiftPM repository with a detailed self-contained reproduction example and expected behavior. Thanks!
